# .github/release-drafter.yml

# Configuration for release-drafter: https://github.com/release-drafter/release-drafter

# Name template for the new release/tag: v$RESOLVED_VERSION
# $RESOLVED_VERSION will be the next version based on semantic versioning rules
# applied to labels on merged PRs (major, minor, patch)
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Categories for changes, based on PR labels
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'ci'
      - 'docs'
      - 'refactor'
      - 'style'

# Template for the release body
# $CHANGES will be replaced with the categorized list of changes
template: |
  ## Changes in this release

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

# Automatically label PRs based on branch names (optional but helpful)
autolabeler:
  - label: 'feature'
    branch:
      - '/^feature\/.+/'
  - label: 'fix'
    branch:
      - '/^fix\/.+/'
      - '/^bug\/.+/'
  - label: 'chore'
    branch:
      - '/^chore\/.+/'

# Exclude specific labels from appearing in the release notes
exclude-labels:
  - 'skip-changelog'

# Replacers can clean up PR titles (optional)
# replacers:
#  - search: '/(?:and|&)/i' # Replace 'and' or '&' with ' &'
#    replace: ' &'
