name: Node.js CI

on:
  push:
    branches:
      - master
      - main
  # Trigger on push to master or main branch
  # Only trigger on commit messages containing [release] for release job
  # This is handled in the release job condition
  pull_request:
    branches: ["master, main"]
  # Trigger on pull requests to master or main branch
  workflow_dispatch: # Allow manual triggering from GitHub Actions UI

permissions:
  contents: write # Needed for release creation
  # Default permissions for GITHUB_TOKEN
  actions: read
  checks: write
  security-events: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        node-version: ["22.x"] # Using Node 22 from original file
        # Continue all builds even if one fails

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Node.js with dependency caching
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Cache Electron and builder binaries
      - name: Cache Electron
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\electron
            ~\AppData\Local\electron-builder
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}

      # Install dependencies
      - run: npm ci
      # Removed explicit rimraf install - it's a dev dependency

      # Run Linter
      - name: Lint Check
        run: npm run lint

      # Run tests before building
      - name: Run Tests
        run: npm test

      # Install NSIS on Windows for electron-builder
      - name: Install NSIS
        if: matrix.os == 'windows-latest'
        run: |
          # For electron-builder 26.0.12, we'll let it use its own bundled NSIS
          # Remove any environment variables that might override electron-builder's NSIS path
          if (Test-Path env:ELECTRON_BUILDER_NSIS_PATH) {
            Remove-Item env:ELECTRON_BUILDER_NSIS_PATH
          }
          # Make sure we have the latest npm to avoid any compatibility issues
          npm install -g npm

      # Build Windows Installer (unsigned) using npm script
      - name: Build Windows Installer
        if: matrix.os == 'windows-latest'
        run: npm run dist:win

      # Build DMG (macOS) using npm script
      - name: Build DMG (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run dist:mac
        # Removed explicit dmg-license install

      # Debug: List files in dist/ after build
      - name: List dist files
        run: |
          echo "Listing dist/ contents:"
          ls -R dist || dir dist /s /b dist

      # Upload built installers as artifacts for release job
      - name: Upload installers
        uses: actions/upload-artifact@v4
        with:
          name: installers-${{ matrix.os }}
          # Changed name slightly to remove node version, less noise
          path: |
            dist/**/*.exe
            dist/**/*.dmg
          if-no-files-found: error # Keep error check

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    # Trigger release job only on push to main with [release] in commit message OR manual dispatch
    if: (github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[release]')) || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Download all installer artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist # Download all artifacts into dist directory
          # No specific name needed, download all

      # Debug: List downloaded artifacts
      - name: List downloaded artifacts
        run: ls -R dist

      - name: Create GitHub Release and Upload Installers
        uses: ncipollo/release-action@v1
        with:
          # Artifact path adjusted to match downloaded structure
          artifacts: "dist/installers*/*.exe,dist/installers*/*.dmg"
          token: ${{ secrets.GITHUB_TOKEN }}
          # Using commit SHA for tag to avoid potential conflicts
          tag: release-${{ github.sha }}
          name: "Automated Release ${{ github.run_number }}"
          draft: false
          prerelease: false
